name: Build and Publish

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    env:
      version: 2.0.${{ github.run_number }}${{ github.ref != 'refs/heads/master' && '-prerelease' || '' }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore /p:version=${{ env.version }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: NugetPublish
      if: github.event_name == 'push'
      run: dotnet nuget push ./PersistentQueue/bin/Release/PersistentQueue.${{ env.version }}.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_API_KEY }}
